# Generated by Django 5.0.6 on 2024-06-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("nature", "Nature"),
                    ("cafe", "Cafe"),
                    ("home", "Home"),
                    ("workplace", "Workplace"),
                    ("park", "Park"),
                    ("beach", "Beach"),
                    ("mountain", "Mountain"),
                    ("city", "City"),
                    ("countryside", "Countryside"),
                    ("water", "Water"),
                ],
                default="nature",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="mood",
            field=models.CharField(
                choices=[
                    ("happy", "Happy"),
                    ("sad", "Sad"),
                    ("excited", "Excited"),
                    ("relaxed", "Relaxed"),
                    ("stressed", "Stressed"),
                    ("adventurous", "Adventurous"),
                    ("grateful", "Grateful"),
                    ("lonely", "Lonely"),
                    ("angry", "Angry"),
                    ("in_love", "In Love"),
                ],
                default="happy",
                max_length=32,
            ),
        ),
    ]
