# Generated by Django 5.0.6 on 2024-06-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="rollercoaster",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("in_between", "In Between"),
                    ("high", "High"),
                ],
                default="in_between",
                max_length=32,
            ),
        ),
    ]
