# Generated by Django 3.2.25 on 2024-09-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_rollercoaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_gkvnll', upload_to='images/'),
        ),
    ]
