# Generated by Django 3.2.25 on 2024-09-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rollercoaster',
        ),
    ]
