# Generated by Django 5.0.6 on 2024-06-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="feeling",
            field=models.CharField(
                blank=True,
                choices=[
                    ("happy", "Happy"),
                    ("sad", "Sad"),
                    ("angry", "Angry"),
                    ("excited", "Excited"),
                    ("bored", "Bored"),
                    ("confused", "Confused"),
                ],
                max_length=10,
            ),
        ),
    ]
